---
queue: bazel-lib-default
env:
  CC: /bin/false
workspaces:
  .:
    icon: bazel
    label: bazel-lib
  e2e/smoke:
    icon: bazel
    tasks:
      - test:
          queue: bazel-lib-small
  e2e/coreutils:
    icon: bazel
    tasks:
      - test:
          queue: bazel-lib-small
  e2e/copy_to_directory:
    icon: bazel
    tasks:
      - test:
          queue: bazel-lib-small
  e2e/external_copy_to_directory:
    icon: bazel
    tasks:
      - test:
          queue: bazel-lib-small
tasks:
  - checkout:
      update_strategy: rebase
  - test:
      hooks:
        - type: before_task
          command: vmstat -a -S M -t 1 2>&1 > vmstat.out &
        - type: after_task
          command: cat vmstat.out
      artifact_paths:
        - vmstat.out
  - format:
      queue: bazel-lib-small
  - gazelle:
      queue: bazel-lib-small
  - configure:
      queue: bazel-lib-small
  - buildifier:
      queue: bazel-lib-small
  - delivery:
      auto_deliver: true
      rules:
        - deliverable: 'attr("tags", "\bdeliverable\b", //...)'
          condition:
            branches:
              - main
        - deliverable:
            - //tools/release:tools_delivery
          condition:
            only_on_change: false
            branches:
              - main
  - warming:
      queue: bazel-lib-warming
notifications:
  github: {}
