---
queue: bazel-lib
env:
  CC: /bin/false
workspaces:
  - .
  - e2e/smoke:
      buildifier:
        without: true
  - e2e/coreutils:
      buildifier:
        without: true
  - e2e/copy_to_directory:
      buildifier:
        without: true
  - e2e/external_copy_to_directory:
      buildifier:
        without: true
tasks:
  branch_freshness:
  buildifier:
  test:
